version: 0.2

phases:
  install:
    commands:
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Start build phase
      - docker run --rm -v "$PWD":/project -w /project --name gradle gradle:jdk8 gradle build
